---
name: Validator-Custom-Trim
version: 0.0101
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Triming based on Validator::Custom;
license: perl
resources:
  license: ~
requires:
  Validator::Custom: 0.0206
build_requires:
  Test::More: 0
provides:
  Validator::Custom::Trim:
    file: lib/Validator/Custom/Trim.pm
    version: 0.0101
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
